name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  compile:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: compile client
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

