name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  compile:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: compile client
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    - name: compile client
      run: |
        cd client 
        find . -name "*.js" -exec node --check {} + 



    - name: compile api
      run: |
        cd api
        find . -name "*.js" -exec node --check {} +

